"""Static coding-set registry rows used by :mod:`nwau_py.coding_set_registry`."""

from __future__ import annotations

CODING_SET_FAMILY_ROWS: tuple[dict[str, object], ...] = (
    {
        "system": "ar_drg",
        "display_name": "AR-DRG",
        "aliases": ("ar-drg", "ar_drg", "ar drg"),
        "licensed": True,
        "restriction": "Licensed product; source artefacts may be restricted.",
        "notes": (
            "Repo pricing-year validation already uses this family as the "
            "admitted acute anchor.",
        ),
        "versions": (
            ("2013", "v7.0"),
            ("2014", "v7.0"),
            ("2015", "v7.0"),
            ("2016", "v8.0"),
            ("2017", "v8.0"),
            ("2018", "v9.0"),
            ("2019", "v9.0"),
            ("2020", "v10.0"),
            ("2021", "v10.0"),
            ("2022", "v10.0"),
            ("2023", "v11.0"),
            ("2024", "v11.0"),
            ("2025", "v11.0"),
            ("2026", "v12.0"),
        ),
    },
    {
        "system": "aecc",
        "display_name": "AECC",
        "aliases": ("aecc",),
        "licensed": False,
        "restriction": None,
        "notes": (
            "Emergency-department pricing uses AECC from the 2021 transition onward.",
        ),
        "versions": (
            ("2013", None),
            ("2014", None),
            ("2015", None),
            ("2016", None),
            ("2017", None),
            ("2018", None),
            ("2019", None),
            ("2020", "v1.0_shadow"),
            ("2021", "v1.0"),
            ("2022", "v1.1"),
            ("2023", "v1.1"),
            ("2024", "v1.1"),
            ("2025", "v1.1"),
            ("2026", "v1.1"),
        ),
    },
    {
        "system": "udg",
        "display_name": "UDG",
        "aliases": ("udg",),
        "licensed": False,
        "restriction": None,
        "notes": (
            "The emergency department calculators still accept UDG for the "
            "mapped path.",
        ),
        "versions": (
            ("2013", "URG_v1.4"),
            ("2014", "URG_v1.4"),
            ("2015", "URG_v1.4"),
            ("2016", "URG_v1.4"),
            ("2017", "URG_v1.4"),
            ("2018", "URG_v1.4"),
            ("2019", "URG_v1.4"),
            ("2020", "URG_v1.4"),
            ("2021", "UDG_v1.3"),
            ("2022", "UDG_v1.3"),
            ("2023", "UDG_v1.3"),
            ("2024", "UDG_v1.3"),
            ("2025", "UDG_v1.3"),
            ("2026", "UDG_v1.3"),
        ),
    },
    {
        "system": "tier_2",
        "display_name": "Tier 2",
        "aliases": ("tier-2", "tier_2", "tier 2"),
        "licensed": False,
        "restriction": None,
        "notes": (
            "The repository records the 2026 NEP transition to Tier 2 v10.0.",
        ),
        "versions": (
            ("2013", None),
            ("2014", None),
            ("2015", None),
            ("2016", None),
            ("2017", None),
            ("2018", None),
            ("2019", None),
            ("2020", None),
            ("2021", None),
            ("2022", "v7"),
            ("2023", "v7"),
            ("2024", "v7"),
            ("2025", "v7"),
            ("2026", "v10.0"),
        ),
    },
    {
        "system": "amhcc",
        "display_name": "AMHCC",
        "aliases": ("amhcc",),
        "licensed": False,
        "restriction": None,
        "notes": (
            "Mental-health calculators use AMHCC v1 in the current repository docs.",
        ),
        "versions": (
            ("2013", None),
            ("2014", None),
            ("2015", None),
            ("2016", None),
            ("2017", None),
            ("2018", None),
            ("2019", None),
            ("2020", None),
            ("2021", "v1"),
            ("2022", "v1"),
            ("2023", "v1"),
            ("2024", "v1"),
            ("2025", "v1"),
            ("2026", "v1"),
        ),
    },
    {
        "system": "icd_10_am",
        "display_name": "ICD-10-AM",
        "aliases": ("icd-10-am", "icd_10_am", "icd 10 am"),
        "licensed": True,
        "restriction": (
            "Licensed clinical coding family; downstream extracts may be restricted."
        ),
        "notes": (
            "Repo HAC and AHR source comments currently call out ICD-10-AM "
            "12th edition codes.",
            "Archive code also contains transition handling for later editions.",
        ),
        "versions": (
            ("2013", None),
            ("2014", None),
            ("2015", None),
            ("2016", None),
            ("2017", None),
            ("2018", None),
            ("2019", None),
            ("2020", None),
            ("2021", None),
            ("2022", None),
            ("2023", None),
            ("2024", None),
            ("2025", "12th edition"),
            ("2026", "12th edition"),
        ),
    },
    {
        "system": "achi",
        "display_name": "ACHI",
        "aliases": ("achi",),
        "licensed": True,
        "restriction": (
            "Licensed clinical coding family; downstream extracts may be restricted."
        ),
        "notes": (
            "The registry keeps ACHI aligned with the same edition basis as "
            "the ICD-10-AM coding set.",
        ),
        "versions": (
            ("2013", None),
            ("2014", None),
            ("2015", None),
            ("2016", None),
            ("2017", None),
            ("2018", None),
            ("2019", None),
            ("2020", None),
            ("2021", None),
            ("2022", None),
            ("2023", None),
            ("2024", None),
            ("2025", "12th edition"),
            ("2026", "12th edition"),
        ),
    },
    {
        "system": "acs",
        "display_name": "ACS",
        "aliases": ("acs",),
        "licensed": True,
        "restriction": (
            "Licensed clinical coding family; downstream extracts may be restricted."
        ),
        "notes": (
            "The registry keeps ACS aligned with the same edition basis as "
            "the ICD-10-AM coding set.",
        ),
        "versions": (
            ("2013", None),
            ("2014", None),
            ("2015", None),
            ("2016", None),
            ("2017", None),
            ("2018", None),
            ("2019", None),
            ("2020", None),
            ("2021", None),
            ("2022", None),
            ("2023", None),
            ("2024", None),
            ("2025", "12th edition"),
            ("2026", "12th edition"),
        ),
    },
    {
        "system": "an_snap",
        "display_name": "AN-SNAP",
        "aliases": ("an-snap", "an_snap", "an snap"),
        "licensed": False,
        "restriction": None,
        "notes": (
            "The repository's release notes mention AN-SNAP v5 as unchanged "
            "for the 2026-27 cycle.",
        ),
        "versions": (
            ("2013", None),
            ("2014", None),
            ("2015", None),
            ("2016", None),
            ("2017", None),
            ("2018", None),
            ("2019", None),
            ("2020", None),
            ("2021", None),
            ("2022", None),
            ("2023", None),
            ("2024", None),
            ("2025", "v5"),
            ("2026", "v5"),
        ),
    },
)
